apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
    limits:
      storage: 100Gi
  storageClassName: nfs-client
